### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mansuleman**
Getting started as a separate element
Changed small syntax for description
Renamed Intermediate things to essentials
Moved Testing and Deployment to essentials; added description

### CODE REVIEW

**Comment by mansuleman** [comment]
Please ignore previous pull requests related to Readme.md; creating anew

**Comment by 1602** [comment]
elements-explained and crash-course should be under "getting started" section header. crash course is the first part of getting started: use generators and don't think about each piece of compound project, second part - structure investigation by adding elements one-by-one.

**Comment by mansuleman** [comment]
New pull request opened. 
One thing: not sure they can add one by one on the 2nd step; to do that they should read about each particular element first.

**Comment by 1602** [comment]
It's wrong vision because "read about element" ≠ "learn everything about
element". You don't need to go deeper into routes magic on 'elements
explained', you just need to learn general purpose of routes, where routing
map located (config/routes.js) and what are consequences of this file
modification. this guide doen't make any sence after reading all essentials.

On Mon, Mar 18, 2013 at 1:12 AM, Mansur S notifications@github.com wrote:

> New pull request opened.
> One think: not sure they can add one by one on the 2nd step; to do that
> they should read about each particular element first.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/compoundjs/guides/pull/6#issuecomment-15030996
> .

## 

Thanks,
Anatoliy Chakkaev

**Comment by mansuleman** [comment]
I understand that elems explained is for general purpose, that's why it's in getting started.
Does reading general purpose of objects in elements explained allow to add one by one? I think they can add one by one after reading particular topics from essentials.

**Comment by 1602** [comment]
Nope.

On Mon, Mar 18, 2013 at 10:52 AM, Mansur S notifications@github.com wrote:

> I understand that elems explained is for general purpose, that's why it's
> in getting started.
> Does reading general purpose of objects in elements explained allow to add
> one by one? I think they can add one by one after reading particular topics
> from essentials.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/compoundjs/guides/pull/6#issuecomment-15041419
> .

## 

Thanks,
Anatoliy Chakkaev

**Pull request closed without merging**
