### PR TITLE
Edits to crash-course and the Guides README.md

### PR DESCRIPTION
**Pull request by crispen-smith**
This is the pull we've been talking about to get the doc edits installed.

### CODE REVIEW

**Comment by 1602** [comment]
Awesome!

**Comment by crispen-smith** [comment]
I'm open to doing more as well, a little bit every couple of days if that's something that would be helpful.

**Comment by 1602** [comment]
Documentation is high priority at the moment.
It would be great if you take a look at api docs as well: ./docs/api/*.md
in compoundjs repository (https://github.com/1602/compound)

Don't hesitate to contact me directly if you have some questions or need
clarifications: mail@anatoliy.in

On Fri, Aug 16, 2013 at 7:26 PM, Crispen Smith notifications@github.comwrote:

> I'm open to doing more as well, a little bit every couple of days if
> that's something that would be helpful.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/compoundjs/guides/pull/21#issuecomment-22773518
> .

## 

Thanks,
Anatoliy Chakkaev

**Comment by crispen-smith** [comment]
Yes, I can definitely do that.  There were some parts of what I changed this morning that I wasn't 100% sure on (like adding the extra note on the Request object) so being able to e-mail you directly will be helpful.

**Pull request merged**
